import js from '@eslint/js';
import globals from 'globals';
import tseslint from 'typescript-eslint';
import react from 'eslint-plugin-react';
import reactHooks from 'eslint-plugin-react-hooks';
import reactRefresh from 'eslint-plugin-react-refresh';
import jsxA11y from 'eslint-plugin-jsx-a11y';

/**
 * Flat config, replacing `.eslintrc.cjs`.
 *
 * ESLint 8 went out of support in October 2024 and the eslintrc format went
 * with it. The move is mechanical in the parts that matter — the same rule sets
 * in the same order — with two things that could not carry over:
 *
 * `--ext ts,tsx` is not a flat-config flag. File selection lives here now, in
 * `files`, which is why every block below names it. The scope is deliberately
 * the same as before: TypeScript only, so the handful of `.js` and `.mjs`
 * scripts stay unlinted rather than quietly joining the run. `.mts` is spelled
 * out because a `.ts` glob does not match it, and Vite 8 wants the root configs
 * under that extension — without it they fall to the default parser, which does
 * not know what a type annotation is.
 *
 * `--report-unused-disable-directives` moved into `linterOptions` for the same
 * reason: the flag still works, but a setting that describes the codebase
 * belongs with the config rather than in the npm script.
 *
 * ESLint 10 was the original target and is not taken here. `eslint-plugin-react`
 * (7.37.5) and `eslint-plugin-jsx-a11y` (6.10.2) both cap their peer range at
 * `^9`, and neither has a release that says otherwise. Installing over that is a
 * lie to npm about what was tested together. 9.39.5 is the last version both
 * plugins claim, and it is on the supported side of the line — see ADR 0011 for
 * why that is a decision rather than a delay.
 */
export default tseslint.config(
  {
    ignores: [
      'dist',
      'dev-dist',
      'coverage',
      'playwright-report',
      'test-results',
      /* Native shells: generated by `cap sync` and compiled by Xcode and
         Gradle. Nothing here is hand-written TypeScript. */
      'ios',
      'android',
    ],
  },

  {
    /**
     * Every shared preset is attached through `extends` rather than spread at
     * the top level, and that is the whole reason this block exists.
     *
     * A flat config with no `files` key applies to plain `.js` and `.mjs` files
     * too. Spread as siblings, these five presets pulled the six build scripts and
     * `lighthouserc.js` into the run for the first time — 76 errors, all of them
     * `no-undef` on `process` and `require` in files that are CommonJS on
     * purpose. That is a real gap, but it is not this change: a format migration
     * that also moves the goalposts cannot be reviewed. `extends` pushes the
     * `files` below down into each preset, so the scope stays exactly what
     * `--ext ts,tsx` gave.
     */
    files: ['**/*.{ts,tsx,mts}'],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.recommended,
      react.configs.flat.recommended,
      react.configs.flat['jsx-runtime'],
      jsxA11y.flatConfigs.recommended,
    ],
    linterOptions: {
      reportUnusedDisableDirectives: 'error',
    },
    settings: {
      react: { version: 'detect' },
    },
    rules: {
      /* An unused argument named `_err` is a signature being honoured, not a
         mistake. An unused *variable* still is one. */
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_' },
      ],
      /* Props are typed. `prop-types` would ask for the same shape twice and
         then let the two drift. */
      'react/prop-types': 'off',
    },
  },

  {
    /* The React layer runs in a browser — or, in the native shells, in a
       WebView that is one. */
    files: ['src/**/*.{ts,tsx}'],
    languageOptions: {
      globals: globals.browser,
    },
  },

  {
    /* Everything that runs under node: the Vercel handlers, the code `lib/`
       shares with them, the Playwright specs, and the config files at the root. */
    files: [
      'api/**/*.ts',
      'lib/**/*.ts',
      'e2e/**/*.ts',
      '*.mts',
    ],
    languageOptions: {
      globals: globals.node,
    },
  },

  {
    /* Fast refresh only survives a file that exports components and nothing
       else; the constant-export exemption covers the route and theme objects
       that sit beside them. */
    ...reactRefresh.configs.vite,
    files: ['src/**/*.tsx'],
  },

  {
    /**
     * The hooks plugin's own major.
     *
     * v4 shipped two rules. v7 ships seventeen: the classic pair plus the React
     * Compiler set, which reads for the things that stop a component being
     * safely memoized — state written during render, refs read in the render
     * path, mutation of values React considers frozen.
     *
     * They are enabled here rather than left off, because they are the reason
     * to take the major at all. The two that stay warnings are the two that
     * report on shape rather than on a defect: `exhaustive-deps` has long-lived
     * intentional exceptions in this codebase, and `incompatible-library` fires
     * on third-party code that is not ours to change.
     */
    ...reactHooks.configs.flat['recommended-latest'],
    files: ['src/**/*.{ts,tsx}'],
  },
);
